services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins/Dockerfile
    container_name: jenkins
    ports:
      - "9090:8080"     # Jenkins UI on http://localhost:9090
      - "50000:50000"   # (optional) JNLP agents
    volumes:
      - jenkins_home:/var/jenkins_home   # persist Jenkins config/jobs
      - /var/run/docker.sock:/var/run/docker.sock  # talk to host Docker daemon
    user: root
    entrypoint: >
      /bin/bash -c "
      chmod 666 /var/run/docker.sock &&
      su jenkins -c /usr/local/bin/jenkins.sh
      "
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=true"

volumes:
  jenkins_home:

